title: ""
email: ""
description: ""
baseurl: ""
url: ""

markdown: kramdown

exclude: ["README.md", "CODE_OF_CONDUCT.md", "LICENSE"]

plugins:
- jekyll-autoprefixer
- jekyll-minifier

autoprefixer:
  browsers:
  - ">= 1%"
  - last 1 major version
  - not dead
  - Chrome >= 60
  - Firefox >= 60
  - Edge >= 16
  - iOS >= 10
  - Safari >= 10
  - Android >= 6
  - not Explorer <= 11

jekyll-minifier:
  remove_intertag_spaces: true 
  uglifier_args:
    harmony: true